sudo: required
services:
  - docker

before_install:
  - docker build -t pancham2020/node-react -f Dockerfile.dev .

script:
#-- --coverage is needed so that npm run test does not sit there waiting for user input after running this will ensure npm run test runs and then exits
  - docker run pancham2020/node-react npm run test -- --coverage --exit